imports:
    - { resource: security.yml }

framework:
    charset:       UTF-8
    secret:        %secret%
    error_handler: null
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] }
    translator:    { fallback: %locale% }
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Services



# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java:           %assetic_javapath%
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/ext-utils/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/ext-utils/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping:                true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    # If you set-up your controllers as services, you must set this to false;
    # otherwise your security checks will be performed twice.
    secure_controllers: true

    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false

    # Enabling this setting will add an additional special attribute "IS_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

# FOS\UserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    class:
        model:
            user: Asso\AMBundle\Entity\User
    group:
        class:
            model: Asso\AMBundle\Entity\Group

# Stof\DoctrineExtensions
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default: ~

# We make sure to activate all features of FrameworkExtraBundle (especially DoctrineParamConverter !)
# @TODO: understand why AppKernel is not enough
sensio_framework_extra: ~
