# FOS\UserBundle
fos_user_security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml

fos_user_user:
    resource: @FOSUserBundle/Resources/config/routing/user.xml
    prefix: /user

fos_user_group:
    resource: @FOSUserBundle/Resources/config/routing/group.xml
    prefix: /group

asso_am:
    resource:  "@AssoAMBundle/Resources/config/routing.yml"
    prefix:    /am

asso_site:
    resource:  "@AssoSiteBundle/Resources/config/routing.yml"

asso_book:
    resource:  "@AssoBookBundle/Resources/config/routing.yml"
    prefix:    /book