security:

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_TREASURER, ROLE_SECRETARY]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: asso.user.user_provider
        
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|img|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        main:
            pattern: .*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:       true
            anonymous:    false
            access_denied_url: /error/403

    acl:
        connection: default

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }