security:

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_TREASURER, ROLE_SECRETARY]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: asso_user.user_provider
        
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|img|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: true

        main:
            pattern:            .*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                check_path:     /login_check
            logout:
                path:           /logout
                target:         /
            anonymous:          true

    acl:
        connection: default

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }