services:
    asso.am.ajax_authentification:
        class:  Asso\AMBundle\Listener\AjaxAuthentificationListener
        tags:
            - { name: kernel.listener, priority: 127, event: core.exception, method: onCoreException }