services:
    asso.am.ajax_authentication:
        class:  Asso\AMBundle\Listener\AjaxAuthenticationListener
        tags:
            - { name: kernel.event_listener, priority: 127, event: kernel.exception, method: onKernelException }

    asso.am.asso_selector:
        class:     Asso\AMBundle\Listener\AssoSelectorListener
        arguments: [@session, @security.context, @router]
        tags:
            - { name: kernel.event_listener, priority: -256, event: security.interactive_login, method: onSecurityInteractiveLogin }
            - { name: kernel.event_listener, priority: -256, event: kernel.controller,          method: onKernelController }
            - { name: kernel.event_listener, priority: -256, event: kernel.response,            method: onKernelResponse }