services:
    asso.am.ajax_authentication:
        class:  Asso\AMBundle\Listener\AjaxAuthenticationListener
        tags:
            - { name: kernel.listener, priority: 127, event: core.exception, method: onCoreException }