# Services

services:
    asso_am.pre_execute:
        class:  Asso\AMBundle\Listener\PreExecuteListener
        tags:
            - { name: kernel.listener, priority: 0, event: onCoreController }
            
    asso_am.asso_manager:
        parent:    asso_abstract.repo
        arguments: [Asso\AMBundle\Entity\Asso]