AssoTestHomepage:
    pattern:  /
    defaults: { _controller: AssoTestBundle:Default:index }

AssoTestCreate:
    pattern:  /create
    defaults: { _controller: AssoTestBundle:Default:create }

AssoTestList:
    pattern:  /list.{_format}
    defaults: { _controller: AssoTestBundle:Default:list, _format: html }
    requirements:
        _format: html|htmlraw