homepage:
    pattern:  /
    defaults: { _controller: AssoTestBundle:Default:index }

create:
    pattern:  /create
    defaults: { _controller: AssoTestBundle:Default:create }

list:
    pattern:  /list
    defaults: { _controller: AssoTestBundle:Default:list }
    