parameters:
    asso_material.material.entity.class: Asso\MaterialBundle\Entity\Material
    asso_material.lease.entity.class:    Asso\MaterialBundle\Entity\Lease

services:
    asso_material.material_repository:
        parent:    asso_abstract.repo
        arguments: [%asso_material.material.entity.class%]
        
    asso_material.lease_repository:
        parent:    asso_abstract.repo
        arguments: [%asso_material.lease.entity.class%]

    asso_material.service:
        class:     Asso\MaterialBundle\MaterialService
        arguments: [@asso_material.material_repository, @asso_material.lease_repository]