parameters:
    asso_book.forms.entry.class: Asso\BookBundle\Form\EntryHandler
    asso_book.forms.account.class: Asso\BookBundle\Form\AccountHandler

services:
    asso_book.forms.entry:
        class:     %asso_book.forms.entry.class%
        scope:     request
        arguments: [@request, @asso_book.entry_manager]

    asso_book.forms.account:
        class:     %asso_book.forms.account.class%
        scope:     request
        arguments: [@request, @asso_book.account_manager]