services:
    asso.user.user_provider:
        class:     Asso\UserBundle\UserProvider
        arguments: [@doctrine.orm.entity_manager, @fos_user.util.username_canonicalizer, %fos_user.model.user.class%]